---
engines:
  rubocop:
    exclude_paths:
      - "config/test.yml"
    base_sub_dir: "test/baseDir"
  duplication:
    exclude_paths:
      - "config/test.yml"
    config:
      languages:
        - "ruby"
languages:
  css:
    extensions:
      - "-css.resource"
exclude_paths:
  - "*.md"
  - "spec/**/*"
  - "benchmarks/**/*"
  - "**.min.js"
  - "**/tests/**"
  - "lib/**"
  - "es/**"
  - "script/**"